import React from 'react';
import { 
  Sunrise, 
  Sun, 
  Sunset, 
  Moon, 
  CloudSun, 
  Users,
  Settings,
  LogOut,
  Save,
  ArrowLeft,
  Calendar,
  RefreshCw,
  Info,
  Bell,
  Trash2,
  Edit2,
  Plus,
  Star,
  ChevronRight,
  Link,
  Globe,
  X
} from 'lucide-react';

export const Icons = {
  Fajr: () => <Sunrise className="w-7 h-7 text-emerald-700" aria-hidden="true" />,
  Zuhr: () => <Sun className="w-7 h-7 text-amber-500" aria-hidden="true" />,
  Asr: () => <CloudSun className="w-7 h-7 text-orange-400" aria-hidden="true" />,
  Maghrib: () => <Sunset className="w-7 h-7 text-indigo-400" aria-hidden="true" />,
  Isha: () => <Moon className="w-7 h-7 text-indigo-800" aria-hidden="true" />,
  Jumma: ({ className }: { className?: string } = {}) => <Users className={className || "w-7 h-7 text-emerald-800"} aria-hidden="true" />,
  Settings: () => <Settings className="w-6 h-6" aria-hidden="true" />,
  Logout: () => <LogOut className="w-6 h-6" aria-hidden="true" />,
  Save: () => <Save className="w-6 h-6" aria-hidden="true" />,
  Back: () => <ArrowLeft className="w-6 h-6" aria-hidden="true" />,
  Calendar: () => <Calendar className="w-5 h-5 text-emerald-100" aria-hidden="true" />,
  Refresh: ({ className }: { className?: string } = {}) => <RefreshCw className={className || "w-5 h-5"} aria-hidden="true" />,
  Info: ({ className }: { className?: string } = {}) => <Info className={className || "w-5 h-5 text-emerald-600"} aria-hidden="true" />,
  Bell: ({ className }: { className?: string } = {}) => <Bell className={className || "w-6 h-6"} aria-hidden="true" />,
  Trash: () => <Trash2 className="w-5 h-5" aria-hidden="true" />,
  Edit: () => <Edit2 className="w-5 h-5" aria-hidden="true" />,
  Plus: () => <Plus className="w-5 h-5" aria-hidden="true" />,
  Star: ({ filled, className }: { filled?: boolean; className?: string } = {}) => <Star className={className || `w-5 h-5 ${filled ? 'fill-amber-400 text-amber-400' : ''}`} aria-hidden="true" />,
  ChevronRight: () => <ChevronRight className="w-5 h-5" aria-hidden="true" />,
  Users: ({ className }: { className?: string } = {}) => <Users className={className || "w-6 h-6"} aria-hidden="true" />,
  Link: () => <Link className="w-5 h-5" aria-hidden="true" />,
  Globe: () => <Globe className="w-5 h-5" aria-hidden="true" />,
  Close: () => <X className="w-5 h-5" aria-hidden="true" />
};